### ISSUE TITLE
"Memory access violation"

### ISSUE THREAD

**Issue by slapperpow7** [pdinklag/WrestlingMPireRemix#4]
I compiled the files into an executable using the newest version of Blitz3D, the opening sequence works fine until it tries to load the music. After that I get the error saying "Memory access violation"

**Comment by pdinklag** [comment]
Hm, that's not a lot of information.
I haven't tried this in ages and will try again in a couple of days - but I have no idea just by that description.

**Comment by pdinklag** [comment]
Works fine here with Blitz3D 1.108.
I can't really offer support because the game isn't my product and I didn't change anything related to music. Does the original game work for you? Does it work when you compile from the unmodified sources?

**Comment by slapperpow7** [comment]
Oh, I see my problem. I've been using career edition instead of management edition.
